/**
 * @file Token.h
 * @author Lincoln Scheer (https://github.com/BikeLinc/)
 * @brief Contains token related classes to be generated by 
 * the Lexer when the source code is converted into tokens.
 * @version 0.1
 * @date 2021-11-18
 * 
 * @copyright Copyright (c) 2021
 * 
 */

#include <string>

/**
 * @brief Token type reperesents the different types of
 * Tokens that can be generated.
 * 
 */
enum TokenType {
    KEYWORD,
    IDENTIFIER,
    OPERATOR,
    CONSTANT
};

/**
 * @brief Token class contains all of the information that
 * the Lexer will generate and pass to the parser.
 * 
 */
class Token {
public:
    Token(TokenType type, std::string value, int rowPosition, int colPosition);
    TokenType getType();
    std::string getValue();
    int getRowPosition();
    int getColPosition();
private:
    TokenType m_type;
    std::string m_value;
    int m_rowPosition;
    int m_colPosition;
};