/**
 * @file Token.cpp
 * @author Lincoln Scheer (https://github.com/BikeLinc/)
 * @brief Contains token related classes to be generated by 
 * the Lexer when the source code is converted into tokens.
 * @version 0.1
 * @date 2021-11-18
 * 
 * @copyright Copyright (c) 2021
 * 
 */

#include "Token.h"

Token::Token(TokenType type, std::string value, int rowPosition, int colPosition) {
    this->m_type = type;
    this->m_value = value;
    this->m_rowPosition = rowPosition;
    this->m_colPosition = colPosition;
}

TokenType Token::getType() {
    return m_type;
}

std::string Token::getValue() {
    return m_value;
}

int Token::getRowPosition() {
    return m_rowPosition;
}

int Token::getColPosition() {
    return m_colPosition;
}